parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: mini-website
    database_user: dbuser
    database_password: dbpass

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null