security:

    providers:
        users:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        page_security:
            switch_user: true
            pattern:    ^/
            anonymous: ~
            provider: users
            http_basic: ~
            form_login:
                check_path: _check_path
                login_path: user_login
                default_target_path: page_home
                username_parameter: login[email]
            logout:
                path:   _logout
                target: page_home

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
