<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * @param $email
     * @param $username
     *
     * @return mixed
     */
    public function loadUserByUsernameAndEmail($email, $username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.username=:username')
            ->andWhere('u.email=:email')
            ->setParameter('username', $username)
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();

        return $user;
    }
}
