fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

page_home:
    path:  /
    defaults:
        _controller: AppBundle:HomePage:index

user_login:
    path: /login
    defaults:
        _controller: AppBundle:User:login

_logout:
    path: /logout

offer_create:
    path: /offers/create
    defaults:
        _controller: AppBundle:Offer:create

offer_list:
    path: /offers/
    defaults:
        _controller: AppBundle:Offer:list

offer_item:
    path: /offers/{id}
    defaults:
        _controller: AppBundle:Offer:item