fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

page_home:
    path:  /
    defaults:
        _controller: AppBundle:HomePage:index

user_login:
    path: /login
    defaults:
        _controller: AppBundle:User:login

_logout:
    path: /logout

offer_create:
    path: /offers/create
    defaults:
        _controller: AppBundle:Offer:create

offer_remove:
    path: /offers/remove/{id}
    defaults:
        _controller: AppBundle:Offer:remove

api_offer_remove:
    path: /api/offers/remove
    methods: post
    defaults:
        _controller: AppBundle:Offer:removeApi
    options:
        expose: true

offer_edit:
    path: /offers/edit/{id}
    defaults:
        _controller: AppBundle:Offer:edit

offer_list:
    path: /offers/
    defaults:
        _controller: AppBundle:Offer:list

offer_item:
    path: /offers/{id}
    defaults:
        _controller: AppBundle:Offer:item